(setq dbd:sarcasms
     '("A bad idea whose time has come.  And gone."
        "I think there's a world market for about 5 computers. -- Thomas J. Watson"
        "As a computer, I find your faith in technology amusing."
        "A mistake carried out to perfection."
        "A moment of convenience, a lifetime of regret."
        "A new concept in abuser interfaces."
        "A terminal disease."
        "And you thought we couldn't make it worse."
        "Complex nonsolutions to simple nonproblems."
        "Considered Harmful."
        "Cruising the information-superhighway in my data-Yugo."
        "Dissatisfaction guaranteed."
        "Don't get frustrated without it."
        "Even your dog won't like it."
        "Flaky and built to stay that way."
        "Flawed beyond belief."
        "Foiled again."
        "Form follows malfunction."
        "Garbage at your fingertips."
        "How can something get so bad, so quickly?"
        "Ignorance is our most important resource."
        "It could be worse, but it'll take time."
        "It could happen to you."
        "It didn't even look good on paper."
        "It was hard to write; it should be hard to use."
        "Japan's secret weapon."
        "Let it get in YOUR way."
        "Live the nightmare."
        "More than a mere hindrance.  It's a whole new barrier!"
        "More than enough rope."
        "Never had it, never will."
        "No hardware is safe."
        "One good crash deserves another."
        "Power tools for power fools."
        "Power tools for power losers."
        "Putting new limits on productivity."
        "Simplicity made complex."
        "Some voids are better left unfilled."
        "Sometimes you fill a vacuum and it still sucks."
        "The Cutting Edge of Obsolescence."
        "The Success Disaster"
        "The art of incompetence."
        "The defacto substandard."
        "The first fully modular software disaster."
        "The joke that kills."
        "The problem for your problem."
        "There's got to be a better way."
        "Warn your friends about it."
        "We make excuses."
        "We will dump no core before its time."
        "When uselessness just isn't enough."
        "When you can't afford to be right."
        "You have nothing to lose but your lunch."
        "You laugh now, but you'll be laughing harder later!"
        "You'd better sit down."
       "Reach out and grep someone."
       "UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity. -- Dennis Ritchie"
       "The world is coming to an end. Please log off."
       "Computer dating is fine, if you're a computer. -- Rita May Brown"
       "You'll envy the dead."
       "They have computers, and they may have other weapons of mass destruction. (Janet Reno)"
       "You start coding. I'll go find out what they want."    
       "Standards are industry's way of codifying obsolescence."
       "Don't anthropomorphize computers - they hate it."
       "The Internet is the world's largest library.  It's just that all the books are on the floor. -- John Allen Paulos"
       "After growing wildly for years, the field of computing appears to be reaching its infancy. -- John Pierce"
       "And computers are getting smarter all the time: scientists tell us that soon they will be able to talk to us. (By \"they\" I mean \"computers\": I doubt scientists will ever be able to talk to us.) --Dave Barry"
       "The manual says to insert disk three, but only two will fit."
       "The first rule of intelligent tinkering is to keep all the pieces. -- Aldo Leopold"
       "Today, if you are not confused, you are just not thinking clearly." 
       "Pick up a sesame seed but lose sight of a watermelon. -- Chinese Proverb"
       ))

(setq dbd:proverbs
      '("I think there's a world market for about 5 computers. -- Thomas J. Watson"
        "All parts should go together without forcing. You must remember that the parts you are reassembling were disassembled by you. Therefore, if you can't get them together again, there must be a reason. By all means, do not use a hammer. (1925 IBM Maintenence Manual)"
        "Technical people are better off not looking at patents. If somebody sues you, you change the algorithm or you just hire a hit-man to whack the stupid git. (Linus Torvalds)"
        "I will master something, then the creativity will come. -- Japanese Proverb"
        "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep. -- Scott Adams"
        "A hunch is creativity trying to tell you something. -- Frank Capra"
        "The secret to creativity is knowing how to hide your sources. -- Albert Einstein"
        "Creative minds have always been known to survive any kind of bad training. -- Anna Freud" 
        "To live a creative life, we must lose our fear of being wrong. -- Joseph Chilton Pearce" 
        "The real problem is not whether machines think but whether men do. (B. F. Skinner)"
        "Kirk: Do you want to know something? Everybody's human.
Spock: I find that remark insulting. (\"Star Trek\")"
        "There's an old story about the person who wished his computer were as easy to use as his telephone. That wish has come true, since I no longer know how to use my telephone. (Bjarne Stroustrup)"
        "Who cares how it works, just as long as it gives the right answer? (Jeff Scholnik)"
        "I think and think for months and years. Ninety-nine times, the conclusion is false. The hundredth time I am right. (Albert Einstein)"
        "The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency. (Bill Gates)"
        "That's the thing about people who think they hate computers. What they really hate is lousy programmers. (Larry Niven)"
        "No, no, you're not thinking, you're just being logical. (Niels Bohr)"
        "If you put tomfoolery into a computer, nothing comes out but tomfoolery. But this tomfoolery, having passed through a very expensive machine, is somehow ennobled and no one dares criticize it. (Pierre Gallois)"
        "Man is the best computer we can put aboard a spacecraft...and the only one that can be mass produced with unskilled labor. (Wernher von Braun)"
        "The computer is no better than its program. (Elting Elmore Morison)"
        "Part of the inhumanity of the computer is that, once it is competently programmed and working smoothly, it is completely honest. (Isaac Asimov)"
        "If there's one thing that computers do well, it's to make the same mistake uncountable times at inhuman speed. (Peter Coffee)"
        "640K [of memory] ought to be enough for anybody. -- Bill Gates (1981)"
        "Imagine the disincentive to software development if after months of work another company could come along and copy your work and market it under its own name...without legal restraints to such copying, companies like Apple could not afford to advance the state of the art. -- Bill Gates, 1983 (New York Times, 25 Sep 1983, p. F2)"
        "Bill Gates is just a monocle and a Persian Cat away from being one of the bad guys in a James Bond movie. -- Dennis Miller"
        "The day Microsoft makes something that doesn't suck is probably the day they start making vacuum cleaners. -- Ernest Jan Plugge"
        "It would be just like programmers to shorten 'the year 2000 problem' to 'Y2K'-- exactly the kind of thinking that created this situation in the first place. -- Steven C. Meyer"
        "If you were plowing a field, which would you rather use? Two strong oxen or 1024 chickens ? -- Seymore Cray, about clusters"
        "Memory is like an orgasm. It's a lot better if you don't have to fake it. -- Seymore Cray, on virtual memory"
        "If you torture the data enough, it will confess. -- Ronald Coase"
        "Data expands to fill the space available for storage. -- Parkinson's Law of Data"
        "Managing senior programmers is like herding cats. -- Dave Platt"
        "If the code and the comments disagree, then both are probably wrong. -- Norm Schryer"
        "Premature optimization is the root of all evil. -- Donald E. Knuth" 
        "The generation of random numbers is too important to be left to chance. -- Robert R. Coveyou, Oak Ridge National Laboratory"
        "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim. -- Edsgar W. Dijkstra (1930-2002)"
        "I mean, if 10 years from now, when you are doing something quick and dirty, you suddenly visualize that I am looking over your shoulders and say to yourself: 'Dijkstra would not have liked this', well that would be enough immortality for me. -- Edsgar W. Dijkstra (1930-2002)"
        "It is practically impossible to teach good programming to students that have had a prior exposure to BASIC: as potential programmers they are mentally mutilated beyond hope of regeneration. -- Edsgar W. Dijkstra (1930-2002)" 
        "Program testing can be used to show the presence of bugs, but never to show their absence! -- Edsgar W. Dijkstra (1930-2002)" 
        "Besides a mathematical inclination, an exceptionally good mastery of one's native tongue is the most vital asset of a competent programmer. -- Edsgar W. Dijkstra (1930-2002)"
        "Object-oriented programming is an exceptionally bad idea which could only have originated in California. -- Edsgar W. Dijkstra (1930-2002)" 
        "Simplicity is prerequisite for reliability. -- Edsgar W. Dijkstra (1930-2002)" 
        "The competent programmer is fully aware of the limited size of his own skull. He therefore approaches his task with full humility, and avoids clever tricks like the plague. -- Edsgar W. Dijkstra (1930-2002)" 
        "When there were no computers programming was no problem. When we had a few weak computers, it became a mild problem. Now that we have gigantic computers, programming is a gigantic problem. -- Edsgar W. Dijkstra (1930-2002)" 
        "The danger from computers is not that they will eventually get as smart as men, but that we will meanwhile agree to meet them halfway. -- Bernard Avishai"
        "An apprentice carpenter may want only a hammer and saw, but a master craftsman employs many precision tools. Computer programming likewise requires sophisticated tools to cope with the complexity of real applications, and only practice with these tools will build skill in their use. -- Robert L. Kruse, Data Structures and Program Design"
        "It would appear that we have reached the limits of what it is possible to achieve with computer technology, although one should be careful with such statements, as they tend to sound pretty silly in 5 years. -- John Von Neumann (ca. 1949)"
        "Always be wary of the Software Engineer who carries a screwdriver. -- Robert Paul"
        "Treat your password like your toothbrush.  Don't let anybody else use it, and get a new one every six months. -- Clifford Stoll"
        "Computer language design is just like a stroll in the park. Jurassic Park, that is. (Larry Wall)"        
        "If you don't think carefully, you might think that programming is just typing statements in a programming language. (Ward Cunningham)"
        "A language that doesn't have everything is actually easier to program in than some that do. (Dennis M Ritchie)"
        "Projects promoting programming in natural language are intrinsically doomed to fail. (Edsger Dijkstra)"
        "I fear the the new object-oriented systems may suffer the fate of LISP, in that they can do many things, but the complexity of the class hierarchies may cause them to collapse under their own weight. (Bill Joy)"
        "If we wish to count lines of code, we should not regard them as lines produced but as lines spent. (Edsger Dijkstra)"
        "You can either have software quality or you can have pointer arithmetic, but you cannot have both at the same time. (Bertrand Meyer)"
        "Are you quite sure that all those bells and whistles, all those wonderful facilities of your so called powerful programming languages, belong to the solution set rather than the problem set? (Edsger Dijkstra)"
        "There are only two kinds of programming languages: those people always bitch about and those nobody uses. (Bjarne Stroustrup)"
        "Should array indices start at 0 or 1? My compromise of 0.5 was rejected without, I thought, proper consideration. (Stan Kelly-Bootle)"
        "Voodoo Programming: Things programmers do that they know shouldn't work but they try anyway, and which sometimes actually work, such as recompiling everything. (Karl Lehenbauer)"
        "The C Programming Language - A language which combines the flexibility of assembly language with the power of assembly language."
        "Beware of bugs in the above code; I have only proved it correct, not tried it. -- Donald Knuth"
        "Windows, another fine product from the folks who gave us EDLIN."
        "C makes it easy to shoot yourself in the foot. C++ makes it harder, but when you do, it blows away your whole leg. -- Bjarne Stroustrup"
        "If I were chained to a bench and 'perl' was the only thing that could open the lock, I'd probably cut my hand off. --Gerald Penn"
        "I've never met a human being who would want to read 17,000 pages of documentation, and if there was, I'd kill him to get him out of the gene pool. -- Joseph Costello, President of Cadence"
        "File names are infinite in length where infinity is set to 255 characters. -- Peter Collinson, \"The Unix File System\""
"Debugging is anticipated with distaste, performed with reluctance, and bragged about forever. -- button at the Boston Computer Museum"
        "Bill Gates says no matter how much more power we can supply, he'll develop some really exciting software that will bring the machine to its knees.-- Intel VP David House, In _EE_Times_, 16 October 1989"
        "And it's so portable --- at least, it worked on every VAX that I tried it on. -- Tim McDaniel"
        "Computers are useless.  They can only give you answers. -- Pablo Picasso (1881-1973)"
        "Technology is dominated by two types of people: those who understand what they do not manage, and those who manage what they do not understand. -- Putt's Law"
        "You can't build a reputation on what you're going to do. -- Henry Ford"
        "The best way out is always through. -- Robert Frost" 
        "Don't be afraid to take a big step. You can't cross a chasm in two small jumps. -- David Lloyd George"
        "Advance, and never halt, for advancing is perfection. Advance and do not fear the thorns in the path, for they draw only corrupt blood. -- Kahlil Gibran" 
        "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great. -- Mark Twain"
        "Success is the ability to go from one failure to another with no loss of enthusiasm. -- Winston Churchill" 
        "History will be kind to me, for I intend to write it. -- Winston Churchill" 
        "Gratitude is not only the greatest of virtues, but the parent of all the others. -- Winston Churchill" 
        "No one wants advice -- only corroboration. -- John Steinback" 
        "If you are patient in one moment of anger, you will escape a hundred days of sorrow. -- Chinese Proverb"
        "How much more grievous are the consequences of anger than the causes of it. -- Marcus Aurelius" 
        "The world needs anger. The world often continues to allow evil because it isn't angry enough. -- Bede Jarrett" 
        "He who angers you conquers you. -- Elizabeth Kenny" 
        "Don't worry about people stealing an idea. If it's original, you will have to ram it down their throats. -- Howard Aiken" 
        "The people who oppose your ideas are inevitably those who represent the established order that your ideas will upset. -- Anthony D'Angelo" 
        "One's mind, once stretched by a new idea, never regains its original dimensions. -- Oliver Wendell Holmes" 
        "An invasion of armies can be resisted, but not an idea whose time has come. -- Victor Hugo"
        "The best way to have a good idea is to have lots of ideas. -- Linus Pauling" 
        "You must not give the world what it asks for, but what it needs. -- Edsgar W. Dijkstra (1930-2002)"
        "Computers in the future may weigh no more than 1.5 tons. -- Popular Mechanics, 1949"
        "Computer Science is no more about computers than astronomy is about telescopes.  -- Edsgar W. Dijkstra (1930-2002)"
        "They have computers, and they may have other weapons of mass destruction. (Janet Reno)"
        "As a computer, I find your faith in technology amusing."
        "A courtyard common to all will be swept by none. -- Chinese Proverb"
        "A dimple on the chin, the devil within -- Gaelic Proverb"
        "A drowning man is not troubled by rain. -- Persian Proverb"
        "A man is not honest simply because he never had a chance to steal. -- Yiddish Proverb"
        "A man should live if only to satisfy his curiosity. -- Yiddish Proverb"
        "A table is not blessed if it has fed no scholars. -- Yiddish Proverb"
        "A thief believes everybody steals."
        "A thorn defends the rose, harming only those who would steal the blossom. -- Chinese proverb"
        "I am not afraid of death, I just don't want to be there when it happens. -- Woody Allen"
        "I don't want to achieve immortality through my work... I want to achieve it through not dying. -- Woody Allen"
        "I tended to place my wife under a pedestal. -- Woody Allen"
        "I was thrown out of college for cheating on the metaphysics exam; I looked into the soul of the boy sitting next to me. -- Woody Allen"
        "Endless money forms the sinews of war. -- Cicero"
        "The chief value of money lies in the fact that one lives in a world in which it is overestimated. -- H. L. Mencken"
        "Make money your god and it will plague you like the devil. -- Henry Fielding (1707 - 1754)"
        "The easiest way for your children to learn about money is for you not to have any. -- Katharine Whitehorn"
        "Lack of money is no obstacle. Lack of an idea is an obstacle. -- Ken Hakuta"
        "Butcher the donkey after it finished his job on the mill. -- Chinese Proverb"
        "Crows everywhere are equally black. -- Chinese Proverb"
        "Dismantle the bridge shortly after crossing it. -- Chinese Proverb"
        "Distant water won't quench your immediate thirst. -- Chinese Proverb"
        "Even a hare will bite when it is cornered. -- Chinese Proverb"
        "Flies never visit an egg that has no crack. -- Chinese Proverb"
        "A frog in a well shaft seeing the sky. -- Chinese Saying"
        "Once on a tiger's back, it is hard to alight. -- Chinese Proverb"
        "An overcrowded chicken farm produce fewer eggs. -- Chinese Proverb"
        "Reshape one's foot to try to fit into a new shoe. -- Chinese Proverb"
        "Waiting for a rabbit to hit upon a tree and be killed in order to catch it. -- Chinese Proverb"
        "We are not so much concerned if you are slow as when you come to a halt. -- Chinese Proverb"
        "A weasel comes to say \"Happy New Year\" to the chickens. -- Chinese Proverb"
        "You can't catch a cub without going into the tiger's den. -- Chinese Proverb"
        "You won't help shoots grow by pulling them up higher. -- Chinese Proverb"
        "A child's life is like a piece of paper on which every person leaves a mark. -- Chinese Proverb"
        "A rat who gnaws at a cat's tail invites destruction. -- Chinese Proverb"
        "Deep doubts, deep wisdom; small doubts, little wisdom. -- Chinese Proverb"
        "Dig the well before you are thirsty. -- Chinese Proverb"
        "Do not employ handsome servants. -- Chinese Proverb"
        "Do not remove a fly from your friend's forehead with a hatchet. -- Chinese Proverb"
        "Don't open a shop unless you like to smile. -- Chinese Proverb"
        "He who asks is a fool for five minutes, but he who does not ask remains a fool forever. -- Chinese Proverb"
        "If you bow at all, bow low. -- Chinese Proverb"
        "Raise your sail one foot and you get ten feet of wind. -- Chinese Proverb"
        "Methodology gives those with no ideas something to do"
        "Reality is the murder of a beautiful theory by a gang of ugly facts"
        "Money: There's nothing in the world so demoralizing as money. -- Sophocles (496 BC - 406 BC), Antigone"
        "I am apparently trapped in a limbo of lost souls. -- John Kennedy O'Toole, Confederacy of Dunces"))

(defun dbd:humor()
  (interactive)
  (insert (nth (random (length dbd:sarcasms)) dbd:sarcasms)))
