name: utilities
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  pathos: "any"
  args: "any"
  ebisu:
      path: /home/dbdavidson/dev/open_source/ebisu

# custom <utilities dependencies>

  ebisu: "^0.6.2"
#    git: git://github.com/patefacio/ebisu
#    path: /home/dbdavidson/dev/open_source/ebisu

  xgrep: "^0.0.5"
#  xgrep:
#    path: /home/dbdavidson/dev/open_source/xgrep
#    git: git://github.com/patefacio/xgrep

# end <utilities dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"

# custom <utilities dev dependencies>
# end <utilities dev dependencies>

dependency_overrides:
# custom <utilities dependency overrides>

  ebisu: "^0.6.2"
#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu
#  mongo_dart:
#    path: /home/dbdavidson/dev/open_source/mongo_dart

# end <utilities dependency overrides>

transformers:

# custom <utilities transformers>
# end <utilities transformers>

