name: kitchen_sink
version: 0.0.0
dependencies:
  args: "any"

#  ebisu:
#    git: git://github.com/patefacio/ebisu

#  ebisu_cpp:
#    git: git://github.com/patefacio/ebisu_cpp
    
  json_schema:
    git: git://github.com/patefacio/json_schema
  simple_schema:
    git: git://github.com/patefacio/simple_schema

  path: any
  
#  pub:
#    path: /home/dbdavidson/dev/open_source/pub

  crypto: "^0.9.1"

  system_info: "^0.0.16"

  unittest: ">=0.11.0"

  xml: "^2.2.3"
  test: "^0.12.0"

  prettify: any

  yaml: any

  googleapis: "^0.9.0"

  glob: "^1.1.0"

dependency_overrides:

  quiver: "^0.21.0"

  vector_math: any

#  id: "^1.0.13"

  
  id:
#    git: git://github.com/patefacio/id
    path: /home/dbdavidson/dev/open_source/id

  ebisu:
#    git: git://github.com/patefacio/ebisu
    path: /home/dbdavidson/dev/open_source/ebisu

  magus:
    path: /home/dbdavidson/dev/open_source/magus
    #git: git://github.com/patefacio/magus

  drudge:
    path: /home/dbdavidson/dev/open_source/drudge
    
  ebisu_web_ui:
    git: git://github.com/patefacio/ebisu_web_ui
#    path: /home/dbdavidson/dev/open_source/ebisu_web_ui
    
  ebisu_cpp:
#    git: git://github.com/patefacio/ebisu_cpp    
    path: /home/dbdavidson/dev/open_source/ebisu_cpp

  ebisu_cpp_db:
#    git: git://github.com/patefacio/ebisu_cpp_db        
    path: /home/dbdavidson/dev/open_source/ebisu_cpp_db

  ebisu_pod:
    path: /home/dbdavidson/dev/open_source/ebisu_pod

  ebisu_msgpack:
    #path: /home/dbdavidson/dev/open_source/ebisu_msgpack
    git: git://github.com/patefacio/ebisu_msgpack
    
  ebisu_mongo:
    path: /home/dbdavidson/dev/open_source/ebisu_mongo    

  mongo_dart: "^0.2.8"
  
  json_schema:
    git: git://github.com/patefacio/json_schema

  angular2: "2.0.0-beta.0"

  analyzer: "^0.27.0"
    
  dart_style: "^0.2.2"
#    path: /home/dbdavidson/dev/open_source/dart_style
#    git: git://github.com/dart-lang/dart_style

  args: "^0.13.0"
  
  xgrep:
    git: git://github.com/patefacio/xgrep
#    path: /home/dbdavidson/dev/open_source/xgrep

  collection: "^1.1.0"

  html: "0.13.0"


