name: kitchen_sink
version: 0.0.0
dependencies:
  args: "any"
  id:
    git: git://github.com/patefacio/id
  ebisu:
    git: git://github.com/patefacio/ebisu
  ebisu_cpp:
    git: git://github.com/patefacio/ebisu_cpp
  json_schema:
    git: git://github.com/patefacio/json_schema
  simple_schema:
    git: git://github.com/patefacio/simple_schema

  unittest: ">=0.11.0"

  xml: "^2.2.3"
  test: "^0.12.0"

  prettify: any

  yaml: any

  googleapis: "^0.9.0"

dependency_overrides:

  quiver: "^0.21.0"

  id:
#    git: git://github.com/patefacio/id
    path: /home/dbdavidson/dev/open_source/id

  ebisu:
#    git: git://github.com/patefacio/ebisu
    path: /home/dbdavidson/dev/open_source/ebisu

  magus:
    path: /home/dbdavidson/dev/open_source/magus
    #git: git://github.com/patefacio/magus
    
  ebisu_web_ui:
    git: git://github.com/patefacio/ebisu_web_ui
#    path: /home/dbdavidson/dev/open_source/ebisu_web_ui
    
  ebisu_cpp:
#    git: git://github.com/patefacio/ebisu_cpp    
    path: /home/dbdavidson/dev/open_source/ebisu_cpp

  ebisu_cpp_db:
#    git: git://github.com/patefacio/ebisu_cpp_db        
    path: /home/dbdavidson/dev/open_source/ebisu_cpp_db
    
  json_schema:
    git: git://github.com/patefacio/json_schema

  dart_style: "^0.2.0"
#    path: /home/dbdavidson/dev/open_source/dart_style
#    git: git://github.com/dart-lang/dart_style

  args: "^0.13.0"
  
  xgrep:
#    git: git://github.com/patefacio/xgrep
    path: /home/dbdavidson/dev/open_source/xgrep

  collection: "^1.1.0"

