name: kitchen_sink
version: 0.0.0
dependencies:
  args: "any"

#  simple_schema:
#    git: git://github.com/patefacio/simple_schema


  test: "^1.0.0"

  prettify: any

  yaml: any

  googleapis: "^0.9.0"

  glob: "^1.1.0"

  intl: "^0.15.1"

  csv: "^3.1.2"

  async: "^2.0.7"

dependency_overrides:

  shelf_web_socket: "^0.2.2+2"
  
  utf: "^0.9.0+4"

  mime: "^0.9.6+1"
  
  xml: "^3.0.0"
  
  path: "^1.6.1"
  
  quiver: "^0.29.0"

  vector_math: any

  id:
    path: ../../../id

  ebisu:
    path: ../../../ebisu

  ebisu_rs:
    path: ../../../ebisu_rs

  magus:
    path: ../../../magus

#  sqljocky: "^0.14.1"
  sqljocky:
    path: /Users/dbdavidson/dev/open_source/sqljocky

  crypto: ">=2.0.0 <3.0.0"
    
  postgres: "^0.9.5"

  postgresql: "^0.3.4+1"  


  ebisu_cpp:
    path: ../../../ebisu_cpp

  ebisu_cpp_db:
    path: ../../../ebisu_cpp_db

  ebisu_pod:
    path: ../../../ebisu_pod

  ebisu_mongo:
    path: ../../../ebisu_mongo    

  mongo_dart: "^0.2.8"
  
  json_schema:
    path: ../../../json_schema      

#  angular2: "2.0.0-beta.0"
    
#  dart_style: "^0.2.16"
#    path: ../../../dart_style
#    git: git://github.com/dart-lang/dart_style

  args: "^1.4.3"

  collection: "^1.14.10"  

  dart_style: "^1.1.0"
  
  html: "^0.13.3+1"


