(defun docs:dart() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/books/dart/DartinAction.pdf&"))
(defun docs:dart-spec() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/dart/dart-language-specification.pdf&"))
(defun docs:css-cheat() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/css/css3-cheat-sheet.pdf&"))
(defun docs:magit-cheat() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/RefCards/magitCheatsheet.pdf&"))
(defun docs:apache() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/apache/httpd-docs-2.2.14.en.pdf&"))
(defun docs:pyramid() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/python/pyramid.pdf&"))
(defun docs:sqlalchemy() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/technical/python/sqlalchemy.pdf&"))
(defun docs:resume() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/orgfiles/resume/dbdavidson.pdf&"))
(defun docs:mongodb() (interactive) (org-open-file "/home/dbdavidson/docs/technical/mongodb/mongodb-docs-2011-06-07.pdf"))
(defun docs:pro-git() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/books/Pro_Git_Scott_Chacon.pdf &"))
(defun docs:magit-cheatsheet() (interactive) (org-open-file "/home/dbdavidson/docs/books/magit_cheatsheet.docx"))
(defun docs:rdoc() (interactive) (org-open-file "/home/dbdavidson/docs/technical/ruby/index.html"))
(defun docs:quantlib() (interactive) (org-open-file "/home/dbdavidson/admin/staged_source/quantlib_1_1.staged_source/Docs/html/index.html"))(defun docs:ruby-humble-little-book() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/books/ruby/hlrb.pdf &"))
(defun docs:intro-to-probability() (interactive) (my-shell-command "nohup acroread /home/dbdavidson/docs/books/statistics/amsbook.intro_to_prob.pdf &"))
(defun docs:ruby-core() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/ruby/Ruby-1.9.1-core.chm &"))
(defun docs:ruby-stdlib() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/ruby/Ruby-1.9.1-stdlib.chm &"))
(defun docs:ruby-cheat-sheet() (interactive) (my-shell-command "nohup acroread '/home/dbdavidson/docs/books/ruby/DZone - Essential Ruby.pdf' &"))
(defun docs:quality-matters() (interactive) (org-open-file "/home/dbdavidson/websites/quality_matters/index.html"))
(defun docs:intel-mkl() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/mkl/mkl_manual/index.htm"))
(defun docs:intel-ipp() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/ipp/ipp_documentation.htm"))
(defun docs:intel-tbb() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/tbb/tbb_documentation.htm"))
(defun docs:intel-tbb-tutorial() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/tbb/Tutorial.pdf"))
(defun docs:intel-icc() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/compiler_c/compiler_documentation_c.htm"))
(defun docs:intel-debugger() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/debugger/Getting_Started.htm"))
(defun docs:intel-getting_started() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/tutorials_c/index.htm"))
(defun docs:intel-ssadiag() (interactive) (org-open-file "/opt/intel/composerxe-2011.0.084/Documentation/en_US/ssadiag_docs/index.htm"))
;(defun docs:c++-standard-1998() (interactive)(org-open-file "/home/dbdavidson/docs/technical/c++/INCITS+ISO+IEC+14882-1998.pdf"))
(defun docs:c++() (interactive)(org-open-file "/home/dbdavidson/websites/cppref/index.html"))
(defun docs:c++-standard() (interactive) (org-open-file "/home/dbdavidson/docs/technical/c++/n3092.pdf"))
(defun docs:StrictAliasing() (interactive) (org-open-file "/home/dbdavidson/docs/technical/c++/StrictAliasing.pdf"))
(defun docs:hdf5_user_guide() (interactive) (org-open-file "/home/dbdavidson/docs/technical/HDF5/HDF5_UG_r186.pdf"))
(defun docs:fcs_ruby_docs() (interactive) (org-open-file "/home/dbdavidson/tmp/fcs_ruby_docs/index.html"))
(defun docs:org() (interactive) (org-open-file "/home/dbdavidson/docs/technical/org/org.pdf"))
(defun docs:orgcard() (interactive) (org-open-file "/usr/share/emacs/23.1/etc/refcards/orgcard.pdf"))
(defun docs:hdf5_ref_manual() (interactive) (org-open-file "/home/dbdavidson/docs/technical/HDF5/HDF5_RM_r186.pdf"))
(defun docs:armadillo() (interactive) (org-open-file "/home/dbdavidson/stage/armadillo-0.9.80/docs_tech/index.html"))
(defun docs:sequel() (interactive) (org-open-file "/home/dbdavidson/websites/sequel_docs/index.html"))
(defun docs:boost() (interactive) (org-open-file "/home/dbdavidson/admin/staged_source/boost_1_48_0.staged_source/doc/html/index.html"))
(defun docs:fastformat() (interactive) (org-open-file "/home/dbdavidson/stage/fastformat-0.6.2/doc/html/0.6.2/index.html"))
(defun docs:otl() (interactive) (org-open-file "/home/dbdavidson/websites/otl_docs/index.html"))
(defun docs:c++-tr-perf() (interactive) (org-open-file "/home/dbdavidson/docs/technical/c++/TR18015.pdf"))
(defun docs:c++-opt() (interactive) (org-open-file "/home/dbdavidson/Downloads/optimizing_cpp.pdf"))
(defun docs:dell-manual() (interactive) (shell-command "evince file:///home/dbdavidson/Downloads/4000446.pdf"))
(defun docs:gnus() (interactive) (shell-command "evince file:///home/dbdavidson/Downloads/gnus.pdf"))
(defun docs:linux-redp4285() (interactive) (org-open-file "/home/dbdavidson/docs/technical/linux/redp4285.pdf"))
(defun docs:trading-floor() (interactive) (org-open-file "/home/dbdavidson/docs/trading/Trading_Floor_Architecture-E.pdf"))
(defun docs:wombat() (interactive) (org-open-file "/home/dbdavidson/docs/trading/wombatdg.pdf"))
(defun docs:mysql-chm() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/mysql/refman-5.1-en.chm &"))
(defun docs:doxygen-chm() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/c++/doxygen_manual-1.7.1.chm &"))
(defun docs:bjam-um() (interactive) (org-open-file "/home/dbdavidson/docs/technical/bjam/userman.pdf"))
(defun docs:manpages-chm() (interactive) (my-shell-command "/usr/bin/python /usr/bin/gnochm /home/dbdavidson/docs/manpages.chm &"))
(defun docs:c++-stl() (interactive)(org-open-file "/home/dbdavidson/docs/technical/c++/cppreference-doc-20111029/reference/en.cppreference.com/w/cpp.html"))
(defun docs:optimizing-linux-chm() (interactive) (my-shell-command "/usr/bin/python /usr/bin/gnochm /home/dbdavidson/docs/optimizing_linux.chm &"))
(defun docs:understanding-linux-vmm--chm() (interactive) (my-shell-command "/usr/bin/python /usr/bin/gnochm /home/dbdavidson/docs/understanding_linux_vmm.chm &"))
(defun docs:c++-101-rules() (interactive) (my-shell-command "/usr/bin/python /usr/bin/gnochm /home/dbdavidson/docs/cpp_101_rules.chm &"))

(defun docs:c++-threading() (interactive) (org-open-file "/home/dbdavidson/docs/books/c++/C++ConcurrencyinAction.pdf"))
(defun docs:models_of_comp_programming() (interactive) (org-open-file "/home/dbdavidson/docs/books/ConceptsTechniquesModelsOfCompProgramming.pdf"))
(defun docs:rails-2.3.2() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/ruby/Rails-2.3.2.chm &"))
;(defun docs:porting_64bit() (interactive) (shell-command "evince file:///home/dbdavidson/Downloads/Porting\\ to\\ 64\\ bit.pdf.pdf"))

(defun docs:modern_c++() (interactive) (my-shell-command "/usr/bin/xchm /home/dbdavidson/docs/technical/c++/AlexandrescuModernCpp.chm &"))

(defun docs:stl-ref() (interactive) (org-open-file "/home/dbdavidson/websites/cplusplus/www.cplusplus.com/reference/stl/index.html"))
(defun docs:libstdc++() (interactive) (org-open-file "/home/dbdavidson/websites/libstdc++-html.20100312/index.html"))
(defun docs:hypothesis-testing() (interactive) (org-open-file "/home/dbdavidson/docs/technical/statistics/hypotesting.pdf"))
(defun docs:power-of-hypothesis-testing() (interactive) (org-open-file "/home/dbdavidson/docs/technical/statistics/power.pdf"))
(defun docs:eviews-um-2() (interactive) (my-shell-command "nohup acroread '/home/dbdavidson/docs/technical/eviews/EViews 7 Users Guide II.pdf' &"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; D docs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun docs:d:tdpl() (interactive) (my-shell-command "nohup ebook-viewer '/home/dbdavidson/calibre_library/Alexandrescu, Andrei/The D Programming Language (215)/The D Programming Language - Alexandrescu, Andrei.mobi' > /dev/null 2>&1 &"))
(defun docs:d:language-spec() (interactive) (my-shell-command "nohup ebook-viewer '/home/dbdavidson/calibre_library/Bright, Walter/D Programming Language Specification (176)/D Programming Language Specification - Bright, Walter.mobi' > /dev/null 2>&1 &"))
(defun docs:d:phobos() (interactive) (my-shell-command "nohup acroread '/home/dbdavidson/docs/technical/dlang/Phobos.2.060.API.pdf' > /dev/null 2>&1 &"))
(defun docs:d:templates() (interactive) (my-shell-command "nohup acroread '/home/dbdavidson/docs/technical/dlang/dtemplates.pdf' > /dev/null 2>&1 &"))
(defun docs:d:style() (interactive) (org-open-file "/home/dbdavidson/docs/technical/dlang/d_style/index.html"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Plusauri docs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun docs:p:taxes_made_simple() (interactive) (my-shell-command "nohup ebook-viewer '/home/dbdavidson/calibre_library/Piper, Mike/Taxes Made Simple_ Income Taxes Explained in 100 Pages or Less (123)/Taxes Made Simple_ Income Taxes Explained in 100 Pages or Less - Piper, Mike.mobi' > /dev/null 2>&1 &"))
(defun docs:p:tax_sched() (interactive) (my-shell-command "nohup acroread '/home/dbdavidson/plusauri/docs/taxes/i1040tt.pdf' > /dev/null 2>&1 &"))

