(defun windowsToLinux(p) (interactive "sPath:")
       (if (null (string-match "XEmacs" emacs-version))
           (replace-regexp-in-string "\\\\" "/" p t)
           (replace-in-string p "\\\\" "/" t)
           ))
       
(defun linuxToWindows(p) (interactive "sPath:")
       (if (null (string-match "XEmacs" emacs-version))
           (replace-regexp-in-string "/" "\\\\" p t)
           (replace-in-string p "/" "\\\\" t)
           ))
