(defvar dbd:*original-load-path* load-path)
(setq load-path (append (list myemacs (concat myemacs "ruby-mode")) dbd:*original-load-path*))

(require 'ruby-mode)
(require 'ruby-electric)
(defun my-ruby-mode-hook ()
  (setq standard-indent 2)
  (ruby-electric-mode t))
(add-hook 'ruby-mode-hook 'my-ruby-mode-hook)
(autoload 'ruby-mode "ruby-mode" "Major mode for editing ruby scripts." t)
(setq auto-mode-alist  (cons '(".rb$" . ruby-mode) auto-mode-alist))
(setq auto-mode-alist  (cons '(".rspec$" . ruby-mode) auto-mode-alist))
(setq auto-mode-alist  (cons '(".tmpl$" . ruby-mode) auto-mode-alist))
(setq auto-mode-alist  (cons '(".rhtml$" . html-mode) auto-mode-alist))

;(add-to-list 'load-path "/home/dbdavidson/install/ruby-debug-extra-0.10.3/share/emacs/site-lisp/")
(add-to-list 'load-path "/home/dbdavidson/fcs/myemacs/elisp/rdebug")
(add-to-list 'load-path "/home/dbdavidson/fcs/myemacs/elisp/ruby-debug-extra-0.10.3")
(require 'rdebug)
(setq rdebug-many-windows nil)
